<?php

$_lang['saas'] = "SaaS";
$_lang['saas.desc'] =  "Software as a Service (SaaS) application theme.";

$_lang['saas.group.company'] = 'Company';
$_lang['setting_saas.setting.site_name'] = 'Company Name';
$_lang['setting_saas.setting.site_name_desc'] = 'The name of your company.';
$_lang['setting_saas.setting.contact_email'] = 'Email Address';
$_lang['setting_saas.setting.contact_email_desc'] = 'The email address to send contact requests to.';
$_lang['setting_saas.setting.contact_phone'] = 'Phone Number';
$_lang['setting_saas.setting.contact_phone_desc'] = 'The phone number to display on the contact page.';
$_lang['setting_saas.setting.contact_phone_ext'] = 'Phone Extension';
$_lang['setting_saas.setting.contact_phone_ext_desc'] = 'The phone extension for the contact phone number.';
$_lang['setting_saas.setting.contact_address'] = 'Address';
$_lang['setting_saas.setting.contact_address_desc'] = 'The address to display on the contact page.';

$_lang['saas.group.cta'] = 'CTA';
$_lang['setting_saas.setting.cta_button'] = 'Button Text';
$_lang['setting_saas.setting.cta_button_desc'] = 'The text for the CTA button.';
$_lang['setting_saas.setting.cta_link'] = 'Page Link';
$_lang['setting_saas.setting.cta_link_desc'] = 'The page to link the CTA button to.';
$_lang['setting_saas.setting.border_radius'] = 'Round Corners';
$_lang['setting_saas.setting.border_radius.square'] = 'Square';
$_lang['setting_saas.setting.border_radius.slightly_rounded'] = 'Slightly Rounded';
$_lang['setting_saas.setting.border_radius.rounded'] = 'Rounded';
$_lang['setting_saas.setting.border_radius.very_rounded'] = 'Very Rounded';
$_lang['setting_saas.setting.border_radius.extremely_rounded'] = 'Extremely Rounded';
$_lang['setting_saas.setting.border_radius.pill'] = 'Pill';
$_lang['setting_saas.setting.border_radius.default'] = 'Default';
$_lang['setting_saas.setting.border_radius_desc'] = 'The amount of rounding on the CTA button.';

$_lang['saas.group.blog'] = 'Blog';
$_lang['setting_saas.setting.blog_show'] = 'Blog Article Count';
$_lang['setting_saas.setting.blog_show_desc'] = 'The number of blog articles to show.';
$_lang['setting_saas.setting.blog_resource'] = 'Blog Page';
$_lang['setting_saas.setting.blog_resource_desc'] = 'The page containing the blog articles.';
$_lang['setting_saas.setting.blog_search_resource'] = 'Blog Search Results Page';
$_lang['setting_saas.setting.blog_search_resource_desc'] = 'The page handling search results for the blog.';
$_lang['setting_saas.setting.blog_home_layout'] = 'Blog Home Layout';
$_lang['setting_saas.setting.blog_home_layout_desc'] = 'The layout for the blog home page.';
$_lang['setting_saas.setting.blog_post_layout'] = 'Blog Article Layout';
$_lang['setting_saas.setting.blog_post_layout_desc'] = 'The layout for the blog article page.';

$_lang['saas.group.logo'] = 'Logo';
$_lang['setting_saas.setting.logo_light'] = 'Logo (Light)';
$_lang['setting_saas.setting.logo_light_desc'] = 'The light version of the company logo.';
$_lang['setting_saas.setting.logo_dark'] = 'Logo (Dark)';
$_lang['setting_saas.setting.logo_dark_desc'] = 'Optional dark version of the company logo.';
$_lang['setting_saas.setting.logo_width'] = 'Logo Width';
$_lang['setting_saas.setting.logo_width_desc'] = 'The width of the company logo.';
$_lang['setting_saas.setting.logo_height'] = 'Logo Height';
$_lang['setting_saas.setting.logo_height_desc'] = 'The height of the company logo.';
$_lang['setting_saas.setting.show_company'] = 'Show Company Name';
$_lang['setting_saas.setting.show_company_desc'] = 'Show the company name next to the logo.';

$_lang['saas.group.social'] = 'Social';
$_lang['setting_saas.setting.social_fa'] = 'Facebook';
$_lang['setting_saas.setting.social_fa_desc'] = 'The Facebook page for the company.';
$_lang['setting_saas.setting.social_tw'] = 'Twitter/X';
$_lang['setting_saas.setting.social_tw_desc'] = 'The Twitter page for the company.';
$_lang['setting_saas.setting.social_li'] = 'LinkedIn';
$_lang['setting_saas.setting.social_li_desc'] = 'The LinkedIn page for the company.';
$_lang['setting_saas.setting.social_in'] = 'Instagram';
$_lang['setting_saas.setting.social_in_desc'] = 'The Instagram page for the company.';
$_lang['setting_saas.setting.social_yt'] = 'YouTube';
$_lang['setting_saas.setting.social_yt_desc'] = 'The YouTube page for the company.';

$_lang['saas.group.colors'] = 'Colors';
$_lang['setting_saas.setting.color_primary'] = 'Primary Color';
$_lang['setting_saas.setting.color_primary_desc'] = 'The primary color for the site.';
$_lang['setting_saas.setting.color_secondary'] = 'Secondary Color';
$_lang['setting_saas.setting.color_secondary_desc'] = 'The secondary color for the site.';
$_lang['setting_saas.setting.color_success'] = 'Success Color';
$_lang['setting_saas.setting.color_success_desc'] = 'The success color for the site.';
$_lang['setting_saas.setting.color_danger'] = 'Danger Color';
$_lang['setting_saas.setting.color_danger_desc'] = 'The danger color for the site.';
$_lang['setting_saas.setting.color_warning'] = 'Warning Color';
$_lang['setting_saas.setting.color_warning_desc'] = 'The warning color for the site.';
$_lang['setting_saas.setting.color_info'] = 'Info Color';
$_lang['setting_saas.setting.color_info_desc'] = 'The info color for the site.';
$_lang['setting_saas.setting.color_light'] = 'Light Color';
$_lang['setting_saas.setting.color_light_desc'] = 'The light color for the site.';
$_lang['setting_saas.setting.color_dark'] = 'Dark Color';
$_lang['setting_saas.setting.color_dark_desc'] = 'The dark color for the site.';
$_lang['setting_saas.setting.color_body_bg'] = 'Body Background Color';
$_lang['setting_saas.setting.color_body_bg_desc'] = 'The background color for the site.';
$_lang['setting_saas.setting.color_body_text'] = 'Body Text Color';
$_lang['setting_saas.setting.color_body_text_desc'] = 'The text color for the site.';
$_lang['setting_saas.setting.color_link'] = 'Link Color';
$_lang['setting_saas.setting.color_link_desc'] = 'The color for links on the site.';
$_lang['setting_saas.setting.color_link_hover'] = 'Link Hover Color';
$_lang['setting_saas.setting.color_link_hover_desc'] = 'The color for links on hover.';
$_lang['setting_saas.setting.color_heading'] = 'Heading Color';
$_lang['setting_saas.setting.color_heading_desc'] = 'The color for headings on the site.';

$_lang['saas.group.fonts'] = 'Fonts';
$_lang['setting_saas.setting.font_sans'] = 'Sans-serif Font';
$_lang['setting_saas.setting.font_sans_desc'] = 'The sans-serif font for the site.';
$_lang['setting_saas.setting.font_serif'] = 'Serif Font';
$_lang['setting_saas.setting.font_serif_desc'] = 'The serif font for the site.';
$_lang['setting_saas.setting.font_mono'] = 'Monospace Font';
$_lang['setting_saas.setting.font_mono_desc'] = 'The monospace font for the site.';

$_lang['saas.group.layout'] = 'Layout';
$_lang['setting_saas.setting.header'] = 'Header Chunk';
$_lang['setting_saas.setting.header_desc'] = 'The chunk to use for the header.';
$_lang['setting_saas.setting.footer'] = 'Footer Chunk';
$_lang['setting_saas.setting.footer_desc'] = 'The chunk to use for the footer.';
